language: python
dist: trusty
sudo: false

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib,pandas numpy scipy matplotlib pandas
  - pip install networkx
  - pip install beautifulsoup4
  - pip install tabulate
  - pip install termcolor html

cache: pip

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran
      - libboost1.55-all-dev

script: make mock-flow
