language: python

install:
  - (cd ci/travis/ && bash setup.sh)
  - travis_wait pip install scipy --user
  - pip install matplotlib --user
  - pip install networkx --user
  - pip install beautifulsoup4 --user
  - travis_wait pip install pandas --user
  - pip install tabulate --user
  - pip install termcolor html --user

sudo: false

cache:
  - pip
  - apt

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran
      - libboost1.55-all-dev
      - g++-4.9

before_script:
  - mkdir build
  - cd build
  - INCLUDE=../ci/travis/eigen CXX="g++-4.9" cmake ..
  - cd ..

script: CXX="g++-4.9" make mock-flow
