language: python
python:
  - "2.7"

install: travis_wait pip install -r requirements.txt

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran

script: nosetests
