language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - libboost1.55-all-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
