language: cpp

compiler:
  - gcc

install:
  - (cd ci/travis/ && bash setup.sh)
  - pip install scipy matplotlib networkx beautifulsoup4

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - libboost1.55-all-dev
      - g++-4.8

before_script:
  - cd scripts && python spark.py -d -t dfe_mock -p ../params.json -b ../test-benchmark -rep html && cd ..
  - mkdir build
  - cd build
  - INCLUDE=../ci/travis/eigen CXX="g++-4.8" cmake ..

script: make
