language: python
dist: trusty
sudo: false

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,matplotlib,pandas numpy scipy matplotlib pandas
  - (cd ci/travis/ && bash setup.sh)
  - pip install networkx
  - pip install beautifulsoup4
  - pip install tabulate
  - pip install termcolor html

cache: pip

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran
      - libboost1.55-all-dev


before_script:
  - mkdir build
  - cd build
  - INCLUDE=../ci/travis/eigen CXX="g++-4.9" cmake ..
  - cd ..

script: make mock-flow
