language: cpp

compiler:
  - gcc

install:
  - (cd ci/travis/ && bash setup.sh)
  - pip install scipy matplotlib networkx beautifulsoup4 pandas tabulate termcolor html --user

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran
      - libboost1.55-all-dev
      - g++-4.8

before_script:
  - mkdir build
  - cd build
  - INCLUDE=../ci/travis/eigen CXX="g++-4.8" cmake ..
  - cd ..

script: CXX="g++-4.8" make mock-flow
